--------------------------------------------------------
--  Arquivo criado - segunda-feira-outubro-07-2024   
--------------------------------------------------------
DROP TABLE "XXBBTSDEVOPS"."TEMP_CARGA_AZURE";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_BUILD";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_LTC";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_PIPELINE";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_COMMIT";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_FILE";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_PDTIC_PROJETOS";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_CONTROLE_REPROCESSAMENTO_TMP";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_FERIADOS";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO";
DROP TABLE "XXBBTSDEVOPS"."XXBBTS_TB_ATUALIZACAO_MOTS";
--------------------------------------------------------
--  DDL for Table TEMP_CARGA_AZURE
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."TEMP_CARGA_AZURE" 
   (	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SG_AZ_PRODUTO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_AZ_TIME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SG_AZ_TIME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA_JSON" BLOB, 
	"AZ_PRODUTO_TIPO_DE_WIT" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"AZ_PRODUTO_TAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" 
   (	"ID_PRODUTO_TIME" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SG_AZ_PRODUTO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_AZ_TIME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SG_AZ_TIME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"DATA_JSON" CLOB COLLATE "USING_NLS_COMP", 
	"TIPO_DE_WIT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"TAGS" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO"."ID_PRODUTO_TIME" IS 'ID Interno';
  GRANT SELECT ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" TO "USR_ANALYTICS";
  GRANT SELECT ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" TO "XXBBTSDEVOPSELECT";
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO_BUILD
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_BUILD" 
   (	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"DATA_JSON" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO_DATAS
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" 
   (	"ID_PRODUTO_TIME" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SG_AZ_PRODUTO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"DATA_JSON" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO_ITEM
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM" 
   (	"WIT" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SG_AZ_PRODUTO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_AZ_TIME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SG_AZ_TIME" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"DATA_JSON" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO_LTC
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_LTC" 
   (	"ID_WIT" NUMBER, 
	"START_DATE_NEW" DATE, 
	"FINSH_DATE_NEW" DATE, 
	"START_DATE_APROVA" DATE, 
	"FINSH_DATE_APROVA" DATE, 
	"START_DATE__COMMIT" DATE, 
	"FINSH_DATE_COMMIT" DATE, 
	"START_DATE_VALIDATE" DATE, 
	"FINSH_DATE_VALIDATE" DATE, 
	"START_DATE_DONE" DATE, 
	"FINSH_DATE__DONE" DATE, 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO_PIPELINE
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_PIPELINE" 
   (	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE, 
	"DATA_JSON_PIPELINES" CLOB COLLATE "USING_NLS_COMP", 
	"DATA_JSON_PIPELINES_RUN" CLOB COLLATE "USING_NLS_COMP", 
	"DATA_JSON_PIPELINES_RELEASE" CLOB COLLATE "USING_NLS_COMP", 
	"DATA_JSON_PIPELINES_RELRUNS" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DATA_JSON_PIPELINES") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DATA_JSON_PIPELINES_RUN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DATA_JSON_PIPELINES_RELEASE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DATA_JSON_PIPELINES_RELRUNS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO_REPO_COMMIT
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_COMMIT" 
   (	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"REPO_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"COMMITID" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTHOR_NOME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTHOR_EMAIL" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"AUTHOR_DATA" DATE, 
	"COMMIT_DATA" DATE, 
	"COMENTARIO" VARCHAR2(4000 BYTE) COLLATE "USING_NLS_COMP", 
	"QTDADE_ADD" NUMBER, 
	"QTDADE_EDT" NUMBER, 
	"QTDADE_DEL" NUMBER, 
	"OBJETOS" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("OBJETOS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XXBBTS_AZ_PRODUTO_REPO_FILE
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_FILE" 
   (	"ID_AZ_PRODUTO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"REPO_NAME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"COMMITID" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"ARQUIVO" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTENSAO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCADD" NUMBER(6,0), 
	"LOCEDT" NUMBER(6,0), 
	"LOCEXC" NUMBER(6,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table XXBBTS_PDTIC_PROJETOS
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_PDTIC_PROJETOS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_PDTIC" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DS_PDTIC" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"DS_URL_PWD" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"DT_PREV_INICIO" DATE, 
	"DT_PREV_TERMINO" DATE, 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LASTUPDATE_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table XXBBTS_PSF_COLABORADORES
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES" 
   (	"MATRICULA" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"NOME" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATE_DATE" DATE DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table XXBBTS_SYSAID_TB_ANOTACAO
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" 
   (	"ID" NUMBER(*,0) DEFAULT XXBBTSDEVOPS.XXBBTS_SYSAID_TB_ANOTACAO_SEQ.NEXTVAL, 
	"ID_TICKET" NUMBER(*,0), 
	"UPDATE_TIME" DATE, 
	"NR_ANOTACAO" NUMBER(*,0), 
	"NOME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"USUARIO" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"DT_ANOTACAO" DATE, 
	"ANOTACAO" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ANOTACAO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."ID" IS 'Contador';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."ID_TICKET" IS 'Numero do chamado no Sysaid';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."UPDATE_TIME" IS 'Data da última modificação do Ticket';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."NR_ANOTACAO" IS 'Numerador de comentarios por Ticket';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."NOME" IS 'Nome do usuário que inseriu o comentário';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."USUARIO" IS 'Email do usuário que inseriu o comentário';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."DT_ANOTACAO" IS 'Data/Hora do comentário';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO"."ANOTACAO" IS 'Texto do comentário';
--------------------------------------------------------
--  DDL for Table XXBBTS_SYSAID_TB_ATIVIDADES
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" 
   (	"ID_TICKET" NUMBER(*,0), 
	"NOME_EXIBICAO" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_ATIVIDADE" NUMBER(*,0), 
	"DT_INICIO" DATE, 
	"DT_FIM" DATE, 
	"TEMPO_TOTAL" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_USUARIO" NUMBER(*,0), 
	"DESCRICAO" CLOB COLLATE "USING_NLS_COMP", 
	"LAST_UPDATE" TIMESTAMP (6) DEFAULT SYSDATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRICAO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."ID_TICKET" IS 'Número do Ticket no SysAid';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."NOME_EXIBICAO" IS 'Nome e email do usuário';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."ID_ATIVIDADE" IS 'ID da atividade';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."DT_INICIO" IS 'Data / hora do início da execução da atividade';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."DT_FIM" IS 'Data / hora do fim da execução da atividade';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."TEMPO_TOTAL" IS 'Tempo corrido entre o início e o fim da atividade em HH:MM';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."EMAIL" IS 'Email do usuário da atividade';
   COMMENT ON COLUMN "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES"."ID_USUARIO" IS 'Id do usuário no SysAid';
--------------------------------------------------------
--  DDL for Table XXBBTS_SYSAID_TB_CONTROLE_REPROCESSAMENTO_TMP
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_CONTROLE_REPROCESSAMENTO_TMP" 
   (	"ID_TICKET" NUMBER(*,0), 
	"REPROCESSADO" NUMBER(*,0) DEFAULT 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table XXBBTS_SYSAID_TB_FERIADOS
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_FERIADOS" 
   (	"FERIADO" DATE, 
	"DESC_FERIADO" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_FERIADOS" TO "XXBBTSDEVOPSELECT";
--------------------------------------------------------
--  DDL for Table XXBBTS_SYSAID_TB_TICKET
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" 
   (	"SERVICO_ATIVIDADE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBCATEGORIA" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ID_TICKET" NUMBER(*,0), 
	"DATA_SOLICITACAO" DATE, 
	"TEMPO_AGUARDANDO_APROVACAO" NUMBER(*,0), 
	"TIPO_FUNCIONALIDADE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TITULO" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"SOLICITAR_NOME_USUARIO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"RESOLUCAO" CLOB COLLATE "USING_NLS_COMP", 
	"USUARIO_A_SER_ATENDIDO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CHAMADO_PRINCIPAL" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA_DE_MODIFICACAO" DATE, 
	"MODIFICAR_USUARIO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"ESPECIALISTA_ATRIBUIDO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"USUARIO_SOLICITANTE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"SUBTIPO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"AMBIENTE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"GERAR_NOVA_SENHA_ENVIAR_PARA_O_GESTOR" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"NOME_DA_RESPONSABILIDADE_PEOPLESOFT" CLOB COLLATE "USING_NLS_COMP", 
	"DEPARTAMENTO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_OPERACIONAL_GERAL" NUMBER(*,0), 
	"TEMPO_DE_PRIMEIRO_ATENDIMENTO" NUMBER(*,0), 
	"TEMPO_AGUARDANDO_FORNECEDOR" NUMBER(*,0), 
	"CONTRATO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_OPERACIONAL_N1" NUMBER(*,0), 
	"RESPONSAVEL_PELO_PROCESSO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL_ACTIVITIES_TIME" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCALIDADE_FISICA" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"PRAZO_DE_SLA" DATE, 
	"DATA_DE_ENCERRAMENTO" DATE, 
	"PRIORIDADE" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"GESTOR_EXECUTIVO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_RESPOSTA_N3" NUMBER(*,0), 
	"EQUIPE_DE_ATENDIMENTO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"CATEGORIA" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"GESTOR_IMEDIATO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_OPERACIONAL_N2" NUMBER(*,0), 
	"TIPO_DE_REGISTRO_DE_SERVICO" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_RESPOSTA_N1" NUMBER(*,0), 
	"TEMPO_RESPOSTA_N2" NUMBER(*,0), 
	"STATUS_SLA" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"STATUS_EFITEC" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"DT_INICIO_EFITEC" DATE, 
	"DT_FIM_EFITEC" DATE, 
	"QTD_DIAS_EFITEC" NUMBER(*,0), 
	"TEMPO_TOTAL_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_AGUARDANDO_FORNECEDOR_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_PRIMEIRO_ATENDIMENTO_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_OPERACIONAL_N1_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_OPERACIONAL_N2_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_RESPOSTA_N3_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_RESPOSTA_N2_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_RESPOSTA_N1_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEMPO_PARADO_FORMAT_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"HORA_EFITEC_F" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SOLUCAO" CLOB COLLATE "USING_NLS_COMP", 
	"INFORMACOES_DE_ENCERRAMENTO" CLOB COLLATE "USING_NLS_COMP", 
	"HISTORICO" CLOB COLLATE "USING_NLS_COMP", 
	"SITE_CRBB" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RESOLUCAO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("NOME_DA_RESPONSABILIDADE_PEOPLESOFT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SOLUCAO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("INFORMACOES_DE_ENCERRAMENTO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("HISTORICO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" TO "XXBBTSDEVOPSELECT";
  GRANT SELECT ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" TO "USR_ANALYTICS";
--------------------------------------------------------
--  DDL for Table XXBBTS_SYSAID_TB_TICKET_JSON
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON" 
   (	"ID_TICKET" NUMBER(*,0), 
	"UPDATE_TIME" TIMESTAMP (6), 
	"RESULT" CLOB COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("RESULT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  GRANT SELECT ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON" TO "XXBBTSDEVOPSELECT";
--------------------------------------------------------
--  DDL for Table XXBBTS_SYSAID_TB_USER_SYSAID
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID" 
   (	"ID_USUARIO" NUMBER(38,0), 
	"MATRICULA" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EQUIPE_ATENDIMENTO" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"NOME" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID" TO "XXBBTSDEVOPSELECT";
--------------------------------------------------------
--  DDL for Table XXBBTS_TB_AFASTAMENTO_TERCEIRO
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" 
   (	"MATRICULA" NUMBER, 
	"EMAIL" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA_INICIO" DATE, 
	"DATA_FIM" DATE, 
	"TIPO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"DESCRICAO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA_CRIACAO" DATE, 
	"NOME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"UOR" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"SIGLA" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table XXBBTS_TB_ATUALIZACAO_MOTS
--------------------------------------------------------

  CREATE TABLE "XXBBTSDEVOPS"."XXBBTS_TB_ATUALIZACAO_MOTS" 
   (	"NOME_DO_PRODUTO" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DATA_LIBERACAO" DATE, 
	"DATA_APLICACAO" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEMP_CARGA_AZURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."TEMP_CARGA_AZURE_PK" ON "XXBBTSDEVOPS"."TEMP_CARGA_AZURE" ("ID_AZ_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_PK" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" ("ID_PRODUTO_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_BUILD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_BUILD_PK" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_BUILD" ("ID_AZ_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_DATAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS_PK" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" ("ID_PRODUTO_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_DATAS_IDX01
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS_IDX01" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" ("SG_AZ_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_ITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM_PK" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM" ("WIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_LTC
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_LTC" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_LTC" ("ID_WIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_PIPELINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_PIPELINE_PK" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_PIPELINE" ("ID_AZ_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_DEVOPS_COMMIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_DEVOPS_COMMIT_PK" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_COMMIT" ("ID_AZ_PRODUTO", "REPO_NAME", "COMMITID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_AZ_PRODUTO_REPO_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_FILE_PK" ON "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_FILE" ("ID_AZ_PRODUTO", "REPO_NAME", "COMMITID", "ARQUIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_XXBBTS_PDTIC_PROJETOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."PK_XXBBTS_PDTIC_PROJETOS" ON "XXBBTSDEVOPS"."XXBBTS_PDTIC_PROJETOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_PDTIC_PROJETOS_IDX01
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_PDTIC_PROJETOS_IDX01" ON "XXBBTSDEVOPS"."XXBBTS_PDTIC_PROJETOS" ("ID_PDTIC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_PSF_COLABORADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES_PK" ON "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES" ("MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_PSF_COLABORADORES_INDX01
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES_INDX01" ON "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES" ("NOME", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00196471
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."SYS_C00196471" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ANOTACAO_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO_UN" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" ("ID_TICKET", "USUARIO", "DT_ANOTACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ANOTACAO_UPDATE_TIME_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO_UPDATE_TIME_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" ("UPDATE_TIME", "DT_ANOTACAO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ANOTACAO_ID_TICKET_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO_ID_TICKET_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" ("ID_TICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ANOTACAO_NOME_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO_NOME_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" ("NOME", "USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ATIVIDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES_PK" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" ("ID_ATIVIDADE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ATIVIDADES_TICKET_ID_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES_TICKET_ID_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" ("ID_TICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ATIVIDADES_ID_USUARIO_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES_ID_USUARIO_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ATIVIDADES_DT_INICIO_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES_DT_INICIO_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" ("DT_INICIO", "DT_FIM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_ATIVIDADES_LAST_UPDATE_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES_LAST_UPDATE_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" ("LAST_UPDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_CONTROLE_REPROCESSAMENTO_TMP_ID_TICKET_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_CONTROLE_REPROCESSAMENTO_TMP_ID_TICKET_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_CONTROLE_REPROCESSAMENTO_TMP" ("ID_TICKET", "REPROCESSADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_XXBBTS_SYSAID_TB_FERIADOS_LOOKUP
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."IDX_XXBBTS_SYSAID_TB_FERIADOS_LOOKUP" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_FERIADOS" ("FERIADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_PK" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" ("ID_TICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_TICKET_DATA_SOLICITACAO_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_DATA_SOLICITACAO_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" ("DATA_SOLICITACAO", "DATA_DE_MODIFICACAO", "DATA_DE_ENCERRAMENTO", "DT_INICIO_EFITEC", "DT_FIM_EFITEC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_TICKET_STATUS_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_STATUS_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" ("STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_TICKET_EQUIPE_DE_ATENDIMENTO_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_EQUIPE_DE_ATENDIMENTO_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" ("EQUIPE_DE_ATENDIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_TICKET_UPDATE_TIME_IDX
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_UPDATE_TIME_IDX" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON" ("UPDATE_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_TICKET_JSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON_PK" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON" ("ID_TICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TICKET_JSON_RESULT
--------------------------------------------------------

  CREATE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TICKET_JSON_RESULT" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON" ("RESULT") 
   INDEXTYPE IS "CTXSYS"."CONTEXT" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_SYSAID_TB_USER_SYSAID_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID_UN" ON "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID" ("ID_USUARIO", "EQUIPE_ATENDIMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index XXBBTS_TB_AFASTAMENTO_TERCEIRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO_PK" ON "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" ("DATA_INICIO", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C00195317
--------------------------------------------------------

  CREATE UNIQUE INDEX "XXBBTSDEVOPS"."SYS_C00195317" ON "XXBBTSDEVOPS"."XXBBTS_TB_ATUALIZACAO_MOTS" ("NOME_DO_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TEMP_CARGA_AZURE
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."TEMP_CARGA_AZURE" MODIFY ("ID_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."TEMP_CARGA_AZURE" ADD CONSTRAINT "TEMP_CARGA_AZURE_PK" PRIMARY KEY ("ID_AZ_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" MODIFY ("ID_PRODUTO_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" MODIFY ("ID_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" MODIFY ("SG_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" MODIFY ("ID_AZ_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" MODIFY ("SG_AZ_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_CHK1" CHECK ((DATA_JSON IS JSON)) DISABLE;
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_PK" PRIMARY KEY ("ID_PRODUTO_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO_BUILD
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_BUILD" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_BUILD_CHK1" CHECK ((DATA_JSON IS JSON)) ENABLE;
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_BUILD" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_BUILD_PK" PRIMARY KEY ("ID_AZ_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO_DATAS
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" MODIFY ("ID_PRODUTO_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" MODIFY ("ID_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" MODIFY ("SG_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_DATAS_CHK1" CHECK ((DATA_JSON IS JSON)) ENABLE;
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_DATAS" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_DATAS_PK" PRIMARY KEY ("ID_PRODUTO_TIME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO_ITEM
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM" MODIFY ("ID_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM" MODIFY ("SG_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM" MODIFY ("ID_AZ_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM" MODIFY ("SG_AZ_TIME" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_ITEM" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_ITEM_CHK1" CHECK ((DATA_JSON IS JSON)) DISABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO_LTC
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_LTC" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_LTC" PRIMARY KEY ("ID_WIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO_PIPELINE
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_PIPELINE" MODIFY ("ID_AZ_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_PIPELINE" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_PIPELINE_PK" PRIMARY KEY ("ID_AZ_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO_REPO_COMMIT
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_COMMIT" ADD CONSTRAINT "XXBBTS_DEVOPS_COMMIT_PK" PRIMARY KEY ("ID_AZ_PRODUTO", "REPO_NAME", "COMMITID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_AZ_PRODUTO_REPO_FILE
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_AZ_PRODUTO_REPO_FILE" ADD CONSTRAINT "XXBBTS_AZ_PRODUTO_REPO_FILE_PK" PRIMARY KEY ("ID_AZ_PRODUTO", "REPO_NAME", "COMMITID", "ARQUIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_PDTIC_PROJETOS
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_PDTIC_PROJETOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_PDTIC_PROJETOS" ADD CONSTRAINT "PK_XXBBTS_PDTIC_PROJETOS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_PSF_COLABORADORES
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES" MODIFY ("MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_PSF_COLABORADORES" ADD CONSTRAINT "XXBBTS_PSF_COLABORADORES_PK" PRIMARY KEY ("MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_SYSAID_TB_ANOTACAO
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ANOTACAO" ADD CONSTRAINT "XXBBTS_SYSAID_TB_ANOTACAO_UN" UNIQUE ("ID_TICKET", "USUARIO", "DT_ANOTACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_SYSAID_TB_ATIVIDADES
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" ADD CONSTRAINT "XXBBTS_SYSAID_TB_ATIVIDADES_PK" PRIMARY KEY ("ID_ATIVIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_ATIVIDADES" MODIFY ("LAST_UPDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XXBBTS_SYSAID_TB_FERIADOS
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_FERIADOS" ADD CONSTRAINT "XXBBTS_SYSAID_TB_FERIADOS_PK" PRIMARY KEY ("FERIADO")
  USING INDEX "XXBBTSDEVOPS"."IDX_XXBBTS_SYSAID_TB_FERIADOS_LOOKUP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_SYSAID_TB_TICKET
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET" ADD CONSTRAINT "XXBBTS_SYSAID_TB_TICKET_PK" PRIMARY KEY ("ID_TICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_SYSAID_TB_TICKET_JSON
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_TICKET_JSON" ADD CONSTRAINT "XXBBTS_SYSAID_TB_TICKET_JSON_PK" PRIMARY KEY ("ID_TICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_SYSAID_TB_USER_SYSAID
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID" MODIFY ("EQUIPE_ATENDIMENTO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_SYSAID_TB_USER_SYSAID" ADD CONSTRAINT "XXBBTS_SYSAID_TB_USER_SYSAID_UN" UNIQUE ("ID_USUARIO", "EQUIPE_ATENDIMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_TB_AFASTAMENTO_TERCEIRO
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" MODIFY ("MATRICULA" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" MODIFY ("DATA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" MODIFY ("DATA_FIM" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_TB_AFASTAMENTO_TERCEIRO" ADD CONSTRAINT "XXBBTS_TB_AFASTAMENTO_TERCEIRO_PK" PRIMARY KEY ("DATA_INICIO", "EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table XXBBTS_TB_ATUALIZACAO_MOTS
--------------------------------------------------------

  ALTER TABLE "XXBBTSDEVOPS"."XXBBTS_TB_ATUALIZACAO_MOTS" ADD PRIMARY KEY ("NOME_DO_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
