#community_bridge: 60pportunities-Documentacao
github: horaciovasconcellos
# issuehunt: s60pportunities
# patreon: s60pportunities
thanks_dev: horaciovasconcellos
tidelift: mkdocs/documentation
custom: ["https:/60pportunities.com.br"]
