# Project information
site_name: 60portunities
site_description: Documentação 60pportunities
site_author: Horacio Vasconcellos
site_url: https://60pportunities.com.br
repo_name: documentacao
repo_url: https://github.com/60pportunities/
edit_uri: tree/master/docs
docs_dir: docs
copyright:  >
   Copyright &copy; 2024 Documentação
   <a href="#__consent">Change cookie settings</a>
extra_css:
  - styles/app-theme.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - styles/tablesort.css
  - styles/60pthemas.css
extra_javascript:
  - javascripts/tables.js
  - javascripts/tablesort.js
validation:
  omitted_files: ignore
  absolute_links: ignore
  unrecognized_links: ignore
  anchors: ignore
theme:
  icon:
    repo: fontawesome/brands/git-alt
  logo: img/logo.jpeg
  custom_dir: theme
  highlightjs: true
  features:
    - announce.dismiss
    - commit
    - content.code.annotation
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - version
    - content.footnote.tooltips
  favicon: img/favicon.ico
  name: material
  palette:
   # Palette toggle for light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: deep purple  # light blue
     accent: purple        # indigo
     toggle:
       icon: material/weather-night
       name: Azul da cor do mar
   # Palette toggle for dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: default
     primary: red        # indigo
     accent: deep purple # light blue
     toggle:
       icon: material/weather-sunny
       name: Rock and Roll
plugins:
  - tags:
      enabled: true
  - git-committers:
      #enterprise_hostname: https://github.com/s60pportunities
      repository: https://github.com/60pportunities/documentacao
      branch: main
      #token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
      token:  !!python/object/apply:os.getenv ["GIT_AUTH_TOKEN"]
  - git-authors
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: America/Sao_Paulo
      locale: pt
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: true
      strict: true
# - blog:
#      blog_dir: .
  - search
  - autorefs
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            docstring_style: sphinx
#  - monorepo
  - include-markdown:
      #encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      start: <!--start-->
      end: <!--end-->
  - table-reader
  - glightbox:
      touchNavigation: true
      loop: true
      height: auto
      width: 80%
  - swagger-ui-tag:
       background: White
  - render_swagger
  - mike
  - mermaid2:
      version: 10.0.2
  - minify:
      minify_html: true
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - attr_list
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - abbr
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  analytics:
    provider: google
    property: G-horacio
  consent:
    title: Consentimento
    description: >-
       Utilizamos cookies para reconhecer as suas repetidas visitas e preferências, bem como
       para medir a eficácia da nossa documentação e se os usuários
       encontre o que eles estão procurando. Com o seu consentimento, você está nos ajudando a
       melhorar nossa documentação.
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/horaciovasconcellos
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/horaciovasconcellos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Horacio_Junior
      name: Horacio.Vasconcellos on Twitter
    - icon: fontawesome/brands/mastodon
      name: Horaci.Vasconcellos on Mastodon
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/77678117787
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hor%C3%A1cio-correa-t-de-vasconcellos-j%C3%BAnior-b7788467/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/horacio.vasconcellos/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/horacio.vasconcellos
    - icon: fontawesome/brands/medium
      link: http://60pportunities.com.br
    - icon: fontawesome/brands/pied-piper-alt
      link: https://60pportunities.com.br
    - icon: fontawesome/brands/product-hunt
      link: https://www.producthunt.com/@horacio_vasconcellos
    - icon: fontawesome/brands/slack
      link: https://gitlab.com/horaciovasconcellos
    - icon: fontawesome/brands/discord
      link: http://60pportunities.com.br
    - icon: fontawesome/solid/paper-plane
      mailto: horacio.vasconcellos@gmail.com
#not_in_nav: |

nav:
   - 'Inicio'                                                        :
      - 'Licença'                                                    : 'LICENSE.md'
      - 'Changelog'                                                  : 'CHANGELOG.md'
      - 'Contribuições'                                              : 'CONTRIBUTING.md'
      - 'Codigo de Conduta'                                          : 'CODE_OF_CONDUCT.md'
      - 'Notas'                                                      : 'notas.md'
      - 'Políticas'                                                  : 'politicas.md'
      - 'Segurança'                                                  : 'SECURITY.md'
   - 'Felicidade do imperfeito'                                      :
      - 'Aprender, desaprender e reaprender'                         : 'recipe_60pportunities_felicidade_001.md'
      - 'Entender'                                                   : 'recipe_60pportunities_felicidade_002.md'
   - 'Registro'                                                      :
      - 'Domínio'                                                    : 'recipe_60pportunities_registro_001.md'
      - 'Conta no GitHub'                                            : 'recipe_60pportunities_registro_002.md'
      - 'Pages'                                                      : 'recipe_60pportunities_registro_004.md'
      - 'Pages no Domínio'                                           : 'recipe_60pportunities_registro_005.md'
   - 'Livro'                                                         :
      - 'Introdução'                                                 : 'recipe_60pportunities_livro_cap_000.md'
      - 'Crise do Software (1960-1979)'                              : 'recipe_60pportunities_livro_cap_001.md'
      - 'Abertura Política (1980-1989)'                              : 'recipe_60pportunities_livro_cap_002.md'
      - 'Globalização e capitalismo (1990-1999)'                     : 'recipe_60pportunities_livro_cap_003.md'
      - 'Democratização da tecnologia (2000-2008)'                   : 'recipe_60pportunities_livro_cap_004.md'
      - 'Grande Depressão (2009-2015)'                               : 'recipe_60pportunities_livro_cap_005.md'
      - 'Década Perdida (2016-2020)'                                 : 'recipe_60pportunities_livro_cap_006.md'
      - 'Avanço da vacinação (2021-2025)'                            : 'recipe_60pportunities_livro_cap_007.md'
   - 'Software Development Lifecycle'                             :
      - 'Definições'                                               : 'recipe_60pportunities_livro_sdlc_local_001.md'
      - 'Pastas'                                                   : 'recipe_60pportunities_livro_sdlc_local_002.md'
      - 'Decisões'                                                 : 'recipe_60pportunities_livro_sdlc_local_003.md'
      - 'Ferramentas'                                              : 'recipe_60pportunities_livro_sdlc_local_004.md'
      - 'Padronizaçao de Escrita'                                    : 'recipe_60pportunities_livro_cap_011.md'
      - 'Dívida Técnica'                                             : 'recipe_60pportunities_livro_cap_011_01.md'
      - 'Documentação é Código'                                      : 'recipe_60pportunities_livro_cap_009.md'
      - 'Versionamento'                                              :
        - 'Conceitos e Histórico'                                    : 'recipe_60pportunities_livro_cap_008.md'
        - 'Estrutura do Repositório'                                 : 'recipe_60pportunities_livro_cap_008_01.md'
        - 'Resolvendo Problemas'                                     : 'recipe_60pportunities_livro_cap_008_02.md'
        - 'Hooks Necessárias'                                        : 'recipe_60pportunities_livro_cap_008_03.md'
      - 'Estruturação da Aplicação'                                : 'recipe_60pportunities_livro_sdlc_local_005.md'
      - 'Montagem de Time'                                         : 'recipe_60pportunities_livro_sdlc_local_006.md'
      - 'Planejamento'                                             : 'recipe_60pportunities_livro_cap_020_01.md'
      - 'Escrita de Código'                                        : 'recipe_60pportunities_livro_cap_020_07.md'
      - 'Feature Flag'                                             : 'recipe_60pportunities_livro_cap_020_02.md'
      - 'Segurança'                                                : 'recipe_60pportunities_livro_cap_020_03.md'
      - 'DevOps'                                                   : 'recipe_60pportunities_livro_cap_020_04.md'
      - 'Fluxo'                                                    : 'recipe_60pportunities_livro_cap_020_05.md'
      - 'Secret-Scan'                                              : 'recipe_60pportunities_livro_cap_020_06.md'
      - 'Trabalhe Pequeno'                                         : 'recipe_60pportunities_livro_cap_020_09.md'
      - 'Pull Request'                                             : 'recipe_60pportunities_livro_cap_020_10.md'
      - 'Arquitetura Sw'                                           : 'recipe_60pportunities_livro_cap_020_11.md'
      - 'Bit rot'                                                  : 'recipe_60pportunities_livro_cap_020_12.md'
      - 'Estimativas'                                                : 'recipe_60pportunities_livro_cap_020_13.md'
      - 'Leis da TI'                                                 : 'recipe_60pportunities_livro_cap_099.md'
      - 'Modelagem de Dados'                                         : 'recipe_60pportunities_livro_cap_010.md'
      - 'O funil de Teste'                                           : 'recipe_60pportunities_livro_cap_012.md'
      - 'Vamos dar uma espiada (Observabilidade)'                    : 'recipe_60pportunities_livro_cap_013.md'
      - 'Inteligência Artificial no Desenvolvimento de Software'     : 'recipe_60pportunities_livro_cap_014.md'
      - 'Estimativa'                                                 : 'recipe_60pportunities_livro_cap_018.md'
      - 'Metas e Métricas: A Importância de Medir'                   : 'recipe_60pportunities_livro_cap_015.md'
      - 'IA Verticais'                                               : 'recipe_60pportunities_livro_cap_016.md'
      - 'Engenharia de Software'                                     : 'recipe_60pportunities_livro_cap_conclusao.md'
   - 'Publicações'                                                   :
      - '31-jan-2025 - LinkedIn'                                     : 'recipe_60pportunities_publicacao_001.md'
   - 'Certificação Perguntas'                                        :
      - 'Certiprof DevOps Essentials'                                : 'recipe_60pportunities_certificacao_depc.md'
      - 'GitHub Foundations'                                         : 'recipe_60pportunities_certificacao_ghf.md'
      - 'GitHub Actions'                                             : 'recipe_60pportunities_certificacao_gha.md'
   - 'Projetos'                                      :
      - 'PMI e Standish Group'                       : 'recipe_60pportunities_projetos_standishgroup.md'
   - 'Arquitetura'                                   :
      - 'Application Program Interface'              : 'recipe_60pportunities_conf_arquitetura_api.md'
      - 'Microserviços'                              : 'recipe_60pportunities_conf_arquitetura_microservico.md'
   - 'Dados'                                         :
      - 'Segregation of Duties'                      : 'recipe_60pportunities_conf_data_sod.md'
      - 'Dados Mestres/Referência'                   : 'recipe_60pportunities_conf_data_master.md'
      - 'Central de Cadastro'                        : 'recipe_60pportunities_conf_data_ccadastro.md'
      - 'Dados Ética'                                : 'recipe_60pportunities_conf_data_etica.md'
      - 'Dados Mestres e Referencia'                 : 'recipe_60pportunities_conf_data_master.md'
   - 'Estudos/Aprendizado'                           :
      - 'Inteligencia Artificial'                    : 'recipe_60pportunities_conf_inteligencia_artificial.md'
   - 'Links Úteis para o Aprendizado'                :
      - 'Faça você mesmo'                            : 'recipe_60pportunities_lic_software.md'
      - 'Inteligência Artificial'                    : 'recipe_links_inteligencia_artificial.md'
      - 'Biblioteca Virtual'                         : 'recipe_links_biblioteca_virtual.md'
