#!/bin/bash
if ! command -v action-validator >/dev/null; then
  echo "action-validator não está instalado."
  exit 1
fi
echo "Executando hook de pré-confirmação para ações do GitHub"
scan_count=0
for action in $(git diff --cached --name-only --diff-filter=ACM | grep -E '^\.github/(workflows|actions)/.*\.ya?ml$'); do
  if action-validator "$action"; then
    echo "✅ $action"
  else
    echo "❌ $action"
    exit 1
  fi
  scan_count=$((scan_count+1))
done
echo "action-validator examinou $scan_count GitHub Actions e não encontrou erros!"
