name: 04_wf_nada
on:
  push:
    branches:
      - main
jobs:
  job_04_wf_nada:   # job_name: Unique name for the job
    name: job_04_wf_nada
    runs-on: ubuntu-latest  # Target runner type

    steps:  # List of steps to be executed within the job
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute a command
      run: echo "Hello, GitHub Workflow!"
