name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install mike
      run: pip install mike

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        LASTTAG="1.0.0"
        echo "LASTTAG=$LASTTAG" >> $GITHUB_ENV

    - name: Build and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        MKDOCS_GIT_COMMITTERS_APIKEY : ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
        GH_PAGES: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
        USEREMAIL: ${{ secrets.USEREMAIL }}
      run: |
        git config --global user.name "$USERNAME"
        git config --global user.email "$USEREMAIL"
        git config --global user.password "$GITHUB_TOKEN"
        mike deploy --update-aliases "${LASTTAG}" latest
        mike set-default --push latest
