name: "CodeQL Advanced"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
       - '**/*.md'
       - '**/*.txt' 
  schedule:
    - cron: '34 12 * * 2'
jobs:
steps:
  - shell: bash
    env:
      SUPER_SECRET: ${{ secrets.TOKEN }}
    run: |
      echo "O valor da variável é: ${SUPER_SECRET}"
