name: Publish GitHub Actions Artifacts Example
on:
  push:
    branches: [ main ]
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables on Windows
        run: env
      - name: Verify secrets to env variables (with prefix, include)
        run: |
          [[ " ${{ secrets.TOKEN }}" != "" ]] && echo "TOKEN deve ser desmarcado, obtido  ${{ secrets.TOKEN }}" && exit 1
          true
        shell: bash
      - name: Print secrets
        run: |
          echo "O valor do Token VALOR eh: ${{ secrets.TOKEN }}"
        shell: bash
      - name: Run Commands with various variables
        if: ${{ env.WORKFLOW_VARIABLE == 'WORKFLOW' }}
        env:
          STEP_VARIABLE: STEP
        run: |
          echo "Alo mundo...."
          echo "Esta é the $WORKFLOW_VARIABLE variavel de ambiente."
          echo "Esta é the $JOB_VARIABLE      variavel de ambiente."
          echo "Esta é the $STEP_VARIABLE     variavel de ambiente."      
  github-actions-environment-variables-windows:
    runs-on: windows-latest
    steps:
      - name: Ubuntu GitHub Actions environment variables List
        run: env

  github-actions-environment-variables-macos:
    runs-on: macos-latest
    steps:
      - name: MacOs List of GitHub Actions environment variables
        run: env
