name: Deploy MkDocs

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Explicitly set permissions to allow writing to the repository

    environment:
      name: producao
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'
        ref: main  # Garante que o checkout seja feito na branch main

    - name: Install Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Configurar Git
      run: |
        git config --global user.name "HVasconcellos"
        git config --global user.email "horacio.vasconcellos@gmail.com"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mkdocs mike

    - name: Install dependencies Requirements
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Get latest tag
      id: get_tag
      run: |
        LAST_TAG=$(git tag -l --sort=v:refname | tail -n 1)
        echo "Última tag: $LAST_TAG"
        echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

    - name: Create and switch to changelog branch
      run: |
        git checkout -b changelog-ci-${{ env.LAST_TAG }}

    - name: Create Changelog
      uses: saadmk11/changelog-ci@v1.1.2
      id: changelog_ci
      with:
        changelog_filename: CHANGELOG.md
        release_version: ${{ env.LAST_TAG }}
        committer_username: 'HVasconcellos'
        committer_email: 'horacio.vasconcellos@gmail.com'
        config_file: .github/changelogConfig.yml
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      env:
        LAST_TAG: ${{ env.LAST_TAG }}
        MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
      run: |
        mike deploy --update-aliases "${LAST_TAG}" latest --allow-empty
        mike set-default --push latest --allow-empty
