name: Deploy MkDocs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Explicitly set permissions to allow writing to the repository

    environment:
      name: producao
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'

#    - name: Upload artifact
#      uses: actions/upload-artifact@v4
#      with:
#        name: my-artifact
#        path: path/to/artifact/ # or path/to/artifact

    - name: Set up GitHub token
      run: |
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: Configurar Git
      run: |
        git config --global user.name "HVasconcellos"
        git config --global user.email "horacio.vasconcellos@gmail.com"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  mkdocs mike

    - name: Install git-lfs
      run: |
         sudo apt-get install git-lfs
         git lfs install
         
    - name: Install dependencies Requirements
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Get latest tag
      id: get_tag
      run: |
          LAST_TAG=$(git tag -l --sort=v:refname | head -n 1)
          echo "Última tag: $LAST_TAG"
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

    - name: Create Changelog
      uses: saadmk11/changelog-ci@v1.1.2
      id: changelog_ci
      with:
        changelog_filename: CHANGELOG.md
        release_version: ${{ env.LAST_TAG }}
        committer_username: 'HVasconcellos'
        committer_email: 'horacio.vasconcellos@gmail.com'
        config_file: .github/changelogConfig.yml
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      env:
        LASTTAG: $LAST_TAG
        MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.MKDOCS_GIT_COMMITTERS_APIKEY }}
      run: |
        mike deploy --update-aliases "${LAST_TAG}" latest --allow-empty
        mike set-default --push latest --allow-empty
