name: Wiki Page Created

on:
  gollum

jobs:
  log-wiki-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do reposit칩rio
        uses: actions/checkout@v4

      - name: Registrar evento da wiki
        run: echo "Uma nova p치gina da Wiki foi criada: ${{ github.event.pages[0].title }}"

      - name: Criar issue para rastrear mudan칞as (opcional)
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueTitle = `游늯 Nova p치gina na Wiki: ${{ github.event.pages[0].title }}`;
            const issueBody = `Uma nova p치gina foi criada na Wiki do reposit칩rio: **${{ github.event.pages[0].title }}**.\n\n游댕 [Veja a p치gina](${{ github.event.pages[0].html_url }})`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });

      - name: Notificar no Slack (opcional)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "游닉 Nova p치gina criada na Wiki: ${{ github.event.pages[0].title }}\n游댕 [Veja aqui](${{ github.event.pages[0].html_url }})"
